version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  posts-service:
    build: ./posts_service
    container_name: posts-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/posts/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  comments-service:
    build: ./comments_service
    container_name: comments-service
    ports:
      - "8001:8000"
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/comments/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - posts-service
      - comments-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb_data: